### ISSUE TITLE
Minor clarification

### ISSUE THREAD

**Issue by bjhartin** [slouc/concurrency-in-scala-with-ce#4]
In the shift example you wrote

> Code is pretty straightforward - we have a recursive loop that goes on forever, and all it does is print out some ID ("A" or "B").

On my reading and executing this, the first example with `def loop` prints "A" continually.  (I commented out the 'shift' to match your example).

**Comment by slouc** [comment]
Thanks for the feedback!

I didn't realise this could be confusing, since the very next sentence is:
> What gets printed out when we run the above program is an endless stream of "A"

I will fix the text you quoted into "all it does is print out some ID received as parameter".
